<?php
/**
 * Created by PhpStorm.
 * User: Praesidiarius
 * Date: 21.09.2020
 * Time: 21:23
 */

$this->InlineScript()
    ->appendFile($this->basePath() . '/vendor/oneplace-weos/js/list.js');
?>

<div class="container-fluid">
    <div class="row bg-dark py-2">
        <div class="container text-white">
            <i class="fas fa-info-circle mr-2"></i> Bitte beachten Sie unsere aktuellen Hnweise wegen COVID-19
        </div>
    </div>
    <div class="row home-parallax">
        <a href="/">
            <i class="fas fa-chevron-left fa-2x text-white"></i>
        </a>
        <div style="opacity: .5; margin-top:-34px; padding-top:50px; background:#000; width:100%; height:200px;">
        </div>
        <h2 class="text-center w-100 text-white" style="position:absolute; margin-top:40px;">Dienstleister in <?=$oCity->city?> finden</h2>
    </div>
    <div class="row bg-light py-4" style="background-color:#f8f5f2;">
        <div class="container text-center">
            <h3>Was suchen Sie ?</h3>
            <ul class="list-inline">
                <li class="list-inline-item">
                    <div class="card p-4 listFilterCategory" plc-category-id="14">
                        <span class="labelFull">
                            <i class="fas fa-user-nurse fa-2x"></i><br/>
                        Physio
                        </span>
                        <span class="labelSmall d-none">
                            <i class="fas fa-user-nurse"></i>
                        </span>
                    </div>
                </li>
                <li class="list-inline-item">
                    <div class="card p-4 listFilterCategory" plc-category-id="15">
                        <span class="labelFull">
                            <i class="fas fa-taxi fa-2x"></i><br/>
                        Fahrdienst
                        </span>
                        <span class="labelSmall d-none">
                            <i class="fas fa-taxi"></i>
                        </span>
                    </div>
                </li>
                <li class="list-inline-item">
                    <div class="card p-4 listFilterCategory" plc-category-id="3">
                        <span class="labelFull">
                            <i class="fas fa-cut fa-2x"></i><br/>
                        Coiffeur
                        </span>
                        <span class="labelSmall d-none">
                            <i class="fas fa-cut"></i>
                        </span>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="container">
            <div class="row companyList p-4">
            </div>
        </div>
    </div>
    <!--
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="row">
                    <?=count($aMyContacts)?> Dienstleister
                </div>
                <div class="row">
                    <a href="#" class="btn btn-primary mr-1">Auswärts</a>
                    <a href="#" class="btn btn-outline-primary">Hausbesuch</a>
                </div>
            </div>
            <div class="col-md-8">
                <ul class="list-group">
                    <?php
                    if(count($aMyContacts) > 0) {
                        foreach($aMyContacts as $oContact) { ?>
                            <li class="list-group-item">
                                <div class="row">
                                    <div class="col-md-4">
                                        <img src="//via.placeholder.com/200x100" />
                                        <span class="fa fa-star checked"></span>
                                        <span class="fa fa-star checked"></span>
                                        <span class="fa fa-star checked"></span>
                                        <span class="fa fa-star"></span>
                                        <span class="fa fa-star"></span>
                                    </div>
                                    <div class="col-md-8">
                                        <a href="/random-singleseo-<?=$oContact->getID()?>-<?=$oCity->zip?>">
                                            <?=$oContact->getLabel()?>
                                        </a>
                                    </div>
                                </div>
                            </li>
                    <?php
                        }
                    } else {
                    ?>
                    <li class="list-group-item">
                        <div class="alert alert-info px-4 py-4">
                            Keine Dienstleister in <?=$oCity->city?> gefunden
                        </div>
                    </li>
                   <?php } ?>
                </ul>
            </div>
        </div>
    </div>
</div>
